/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BoardInvite {
    id: bigint;
    createdAt: Time;
    boardId: bigint;
    inviteCode: string;
}
export interface Board {
    id: bigint;
    ownerId: Principal;
    name: string;
    createdAt: Time;
}
export interface Tag {
    id: bigint;
    name: string;
    color: string;
    boardId: bigint;
}
export type Time = bigint;
export interface Column {
    id: bigint;
    name: string;
    createdAt: Time;
    boardId: bigint;
    position: bigint;
}
export interface Card {
    id: bigint;
    title: string;
    assigneeId?: Principal;
    createdAt: Time;
    tags: Array<bigint>;
    description: string;
    boardId: bigint;
    updatedAt: Time;
    position: bigint;
    columnId: bigint;
}
export interface InviteDetails {
    memberCount: bigint;
    boardName: string;
}
export interface BoardMember {
    userId: Principal;
    joinedAt: Time;
    role: string;
    boardId: bigint;
}
export interface ColumnWithCards {
    cards: Array<Card>;
    column: Column;
}
export interface UserSearchResult {
    username: string;
    userId: Principal;
}
export interface UserProfile {
    username: string;
    userId: Principal;
    createdAt: Time;
    email: string;
}
export interface BoardWithDetails {
    members: Array<BoardMember>;
    tags: Array<Tag>;
    board: Board;
    columns: Array<ColumnWithCards>;
}
export interface backendInterface {
    createBoard(name: string): Promise<bigint>;
    createCard(columnId: bigint, title: string, description: string, tagIds: Array<bigint>, assigneeId: Principal | null): Promise<bigint>;
    createColumn(boardId: bigint, name: string): Promise<bigint>;
    createTag(boardId: bigint, name: string, color: string): Promise<bigint>;
    deleteBoard(boardId: bigint): Promise<boolean>;
    deleteCard(cardId: bigint): Promise<boolean>;
    deleteColumn(columnId: bigint): Promise<boolean>;
    deleteTag(tagId: bigint): Promise<boolean>;
    exportBoardCSV(boardId: bigint): Promise<string>;
    generateBoardInvite(boardId: bigint): Promise<string>;
    getBoard(boardId: bigint): Promise<BoardWithDetails | null>;
    getBoardInvites(boardId: bigint): Promise<Array<BoardInvite>>;
    getBoardMemberProfiles(boardId: bigint): Promise<Array<UserProfile>>;
    getBoardMembers(boardId: bigint): Promise<Array<BoardMember>>;
    getBoardTags(boardId: bigint): Promise<Array<Tag>>;
    getInviteDetails(code: string): Promise<InviteDetails | null>;
    getMyBoards(): Promise<Array<Board>>;
    getUserProfile(): Promise<UserProfile | null>;
    getUserProfileByPrincipal(principal: Principal): Promise<UserProfile | null>;
    hasUserProfile(): Promise<boolean>;
    inviteUserToBoard(boardId: bigint, targetPrincipal: Principal): Promise<boolean>;
    joinBoardWithCode(code: string): Promise<bigint>;
    leaveBoard(boardId: bigint): Promise<boolean>;
    lookupUser(searchText: string): Promise<UserSearchResult | null>;
    moveCard(cardId: bigint, targetColumnId: bigint, newPosition: bigint): Promise<boolean>;
    removeMember(boardId: bigint, principalId: Principal): Promise<boolean>;
    reorderCards(columnId: bigint, cardIds: Array<bigint>): Promise<boolean>;
    reorderColumns(boardId: bigint, columnIds: Array<bigint>): Promise<boolean>;
    revokeInvite(code: string): Promise<boolean>;
    setUserProfile(username: string, email: string): Promise<boolean>;
    transferOwnership(boardId: bigint, newOwnerId: Principal): Promise<boolean>;
    updateBoard(boardId: bigint, name: string): Promise<boolean>;
    updateCard(cardId: bigint, title: string, description: string, tagIds: Array<bigint>, assigneeId: Principal | null): Promise<boolean>;
    updateColumn(columnId: bigint, name: string): Promise<boolean>;
    updateTag(tagId: bigint, name: string, color: string): Promise<boolean>;
}
import type { Board as _Board, BoardMember as _BoardMember, BoardWithDetails as _BoardWithDetails, Card as _Card, Column as _Column, ColumnWithCards as _ColumnWithCards, InviteDetails as _InviteDetails, Tag as _Tag, Time as _Time, UserProfile as _UserProfile, UserSearchResult as _UserSearchResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBoard(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBoard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBoard(arg0);
            return result;
        }
    }
    async createCard(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>, arg4: Principal | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCard(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCard(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createColumn(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createColumn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createColumn(arg0, arg1);
            return result;
        }
    }
    async createTag(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTag(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTag(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBoard(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBoard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBoard(arg0);
            return result;
        }
    }
    async deleteCard(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0);
            return result;
        }
    }
    async deleteColumn(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteColumn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteColumn(arg0);
            return result;
        }
    }
    async deleteTag(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTag(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTag(arg0);
            return result;
        }
    }
    async exportBoardCSV(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportBoardCSV(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportBoardCSV(arg0);
            return result;
        }
    }
    async generateBoardInvite(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateBoardInvite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateBoardInvite(arg0);
            return result;
        }
    }
    async getBoard(arg0: bigint): Promise<BoardWithDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoard(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoard(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBoardInvites(arg0: bigint): Promise<Array<BoardInvite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardInvites(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardInvites(arg0);
            return result;
        }
    }
    async getBoardMemberProfiles(arg0: bigint): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardMemberProfiles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardMemberProfiles(arg0);
            return result;
        }
    }
    async getBoardMembers(arg0: bigint): Promise<Array<BoardMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardMembers(arg0);
            return result;
        }
    }
    async getBoardTags(arg0: bigint): Promise<Array<Tag>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardTags(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardTags(arg0);
            return result;
        }
    }
    async getInviteDetails(arg0: string): Promise<InviteDetails | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteDetails(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteDetails(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBoards(): Promise<Array<Board>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBoards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBoards();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByPrincipal(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByPrincipal(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByPrincipal(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserProfile();
            return result;
        }
    }
    async inviteUserToBoard(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteUserToBoard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteUserToBoard(arg0, arg1);
            return result;
        }
    }
    async joinBoardWithCode(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.joinBoardWithCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinBoardWithCode(arg0);
            return result;
        }
    }
    async leaveBoard(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveBoard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveBoard(arg0);
            return result;
        }
    }
    async lookupUser(arg0: string): Promise<UserSearchResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupUser(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupUser(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async moveCard(arg0: bigint, arg1: bigint, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.moveCard(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveCard(arg0, arg1, arg2);
            return result;
        }
    }
    async removeMember(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0, arg1);
            return result;
        }
    }
    async reorderCards(arg0: bigint, arg1: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderCards(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderCards(arg0, arg1);
            return result;
        }
    }
    async reorderColumns(arg0: bigint, arg1: Array<bigint>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderColumns(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderColumns(arg0, arg1);
            return result;
        }
    }
    async revokeInvite(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeInvite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeInvite(arg0);
            return result;
        }
    }
    async setUserProfile(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0, arg1);
            return result;
        }
    }
    async transferOwnership(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.transferOwnership(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferOwnership(arg0, arg1);
            return result;
        }
    }
    async updateBoard(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBoard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBoard(arg0, arg1);
            return result;
        }
    }
    async updateCard(arg0: bigint, arg1: string, arg2: string, arg3: Array<bigint>, arg4: Principal | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateColumn(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateColumn(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateColumn(arg0, arg1);
            return result;
        }
    }
    async updateTag(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTag(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTag(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_BoardWithDetails_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoardWithDetails): BoardWithDetails {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Card_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ColumnWithCards_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColumnWithCards): ColumnWithCards {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InviteDetails]): InviteDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserSearchResult]): UserSearchResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BoardWithDetails]): BoardWithDetails | null {
    return value.length === 0 ? null : from_candid_BoardWithDetails_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    assigneeId: [] | [Principal];
    createdAt: _Time;
    tags: Array<bigint>;
    description: string;
    boardId: bigint;
    updatedAt: _Time;
    position: bigint;
    columnId: bigint;
}): {
    id: bigint;
    title: string;
    assigneeId?: Principal;
    createdAt: Time;
    tags: Array<bigint>;
    description: string;
    boardId: bigint;
    updatedAt: Time;
    position: bigint;
    columnId: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        assigneeId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.assigneeId)),
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        boardId: value.boardId,
        updatedAt: value.updatedAt,
        position: value.position,
        columnId: value.columnId
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    members: Array<_BoardMember>;
    tags: Array<_Tag>;
    board: _Board;
    columns: Array<_ColumnWithCards>;
}): {
    members: Array<BoardMember>;
    tags: Array<Tag>;
    board: Board;
    columns: Array<ColumnWithCards>;
} {
    return {
        members: value.members,
        tags: value.tags,
        board: value.board,
        columns: from_candid_vec_n5(_uploadFile, _downloadFile, value.columns)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cards: Array<_Card>;
    column: _Column;
}): {
    cards: Array<Card>;
    column: Column;
} {
    return {
        cards: from_candid_vec_n8(_uploadFile, _downloadFile, value.cards),
        column: value.column
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ColumnWithCards>): Array<ColumnWithCards> {
    return value.map((x)=>from_candid_ColumnWithCards_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
