/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Board {
  'id' : bigint,
  'ownerId' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export interface BoardInvite {
  'id' : bigint,
  'createdAt' : Time,
  'boardId' : bigint,
  'inviteCode' : string,
}
export interface BoardMember {
  'userId' : Principal,
  'joinedAt' : Time,
  'role' : string,
  'boardId' : bigint,
}
export interface BoardWithDetails {
  'members' : Array<BoardMember>,
  'tags' : Array<Tag>,
  'board' : Board,
  'columns' : Array<ColumnWithCards>,
}
export interface Card {
  'id' : bigint,
  'title' : string,
  'assigneeId' : [] | [Principal],
  'createdAt' : Time,
  'tags' : Array<bigint>,
  'description' : string,
  'boardId' : bigint,
  'updatedAt' : Time,
  'position' : bigint,
  'columnId' : bigint,
}
export interface Column {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'boardId' : bigint,
  'position' : bigint,
}
export interface ColumnWithCards { 'cards' : Array<Card>, 'column' : Column }
export interface InviteDetails { 'memberCount' : bigint, 'boardName' : string }
export interface Tag {
  'id' : bigint,
  'name' : string,
  'color' : string,
  'boardId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'email' : string,
}
export interface UserSearchResult { 'username' : string, 'userId' : Principal }
export interface _SERVICE {
  'createBoard' : ActorMethod<[string], bigint>,
  'createCard' : ActorMethod<
    [bigint, string, string, Array<bigint>, [] | [Principal]],
    bigint
  >,
  'createColumn' : ActorMethod<[bigint, string], bigint>,
  'createTag' : ActorMethod<[bigint, string, string], bigint>,
  'deleteBoard' : ActorMethod<[bigint], boolean>,
  'deleteCard' : ActorMethod<[bigint], boolean>,
  'deleteColumn' : ActorMethod<[bigint], boolean>,
  'deleteTag' : ActorMethod<[bigint], boolean>,
  'exportBoardCSV' : ActorMethod<[bigint], string>,
  'generateBoardInvite' : ActorMethod<[bigint], string>,
  'getBoard' : ActorMethod<[bigint], [] | [BoardWithDetails]>,
  'getBoardInvites' : ActorMethod<[bigint], Array<BoardInvite>>,
  'getBoardMemberProfiles' : ActorMethod<[bigint], Array<UserProfile>>,
  'getBoardMembers' : ActorMethod<[bigint], Array<BoardMember>>,
  'getBoardTags' : ActorMethod<[bigint], Array<Tag>>,
  'getInviteDetails' : ActorMethod<[string], [] | [InviteDetails]>,
  'getMyBoards' : ActorMethod<[], Array<Board>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserProfile' : ActorMethod<[], boolean>,
  'inviteUserToBoard' : ActorMethod<[bigint, Principal], boolean>,
  'joinBoardWithCode' : ActorMethod<[string], bigint>,
  'leaveBoard' : ActorMethod<[bigint], boolean>,
  'lookupUser' : ActorMethod<[string], [] | [UserSearchResult]>,
  'moveCard' : ActorMethod<[bigint, bigint, bigint], boolean>,
  'removeMember' : ActorMethod<[bigint, Principal], boolean>,
  'reorderCards' : ActorMethod<[bigint, Array<bigint>], boolean>,
  'reorderColumns' : ActorMethod<[bigint, Array<bigint>], boolean>,
  'revokeInvite' : ActorMethod<[string], boolean>,
  'setUserProfile' : ActorMethod<[string, string], boolean>,
  'transferOwnership' : ActorMethod<[bigint, Principal], boolean>,
  'updateBoard' : ActorMethod<[bigint, string], boolean>,
  'updateCard' : ActorMethod<
    [bigint, string, string, Array<bigint>, [] | [Principal]],
    boolean
  >,
  'updateColumn' : ActorMethod<[bigint, string], boolean>,
  'updateTag' : ActorMethod<[bigint, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];