/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BoardMember = IDL.Record({
  'userId' : IDL.Principal,
  'joinedAt' : Time,
  'role' : IDL.Text,
  'boardId' : IDL.Nat,
});
export const Tag = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'boardId' : IDL.Nat,
});
export const Board = IDL.Record({
  'id' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const Card = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assigneeId' : IDL.Opt(IDL.Principal),
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Nat),
  'description' : IDL.Text,
  'boardId' : IDL.Nat,
  'updatedAt' : Time,
  'position' : IDL.Nat,
  'columnId' : IDL.Nat,
});
export const Column = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'boardId' : IDL.Nat,
  'position' : IDL.Nat,
});
export const ColumnWithCards = IDL.Record({
  'cards' : IDL.Vec(Card),
  'column' : Column,
});
export const BoardWithDetails = IDL.Record({
  'members' : IDL.Vec(BoardMember),
  'tags' : IDL.Vec(Tag),
  'board' : Board,
  'columns' : IDL.Vec(ColumnWithCards),
});
export const BoardInvite = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'boardId' : IDL.Nat,
  'inviteCode' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'email' : IDL.Text,
});
export const InviteDetails = IDL.Record({
  'memberCount' : IDL.Nat,
  'boardName' : IDL.Text,
});
export const UserSearchResult = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Principal,
});

export const idlService = IDL.Service({
  'createBoard' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createCard' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Principal)],
      [IDL.Nat],
      [],
    ),
  'createColumn' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createTag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteBoard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteColumn' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTag' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'exportBoardCSV' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'generateBoardInvite' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getBoard' : IDL.Func([IDL.Nat], [IDL.Opt(BoardWithDetails)], ['query']),
  'getBoardInvites' : IDL.Func([IDL.Nat], [IDL.Vec(BoardInvite)], ['query']),
  'getBoardMemberProfiles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getBoardMembers' : IDL.Func([IDL.Nat], [IDL.Vec(BoardMember)], ['query']),
  'getBoardTags' : IDL.Func([IDL.Nat], [IDL.Vec(Tag)], ['query']),
  'getInviteDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InviteDetails)],
      ['query'],
    ),
  'getMyBoards' : IDL.Func([], [IDL.Vec(Board)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserProfile' : IDL.Func([], [IDL.Bool], ['query']),
  'inviteUserToBoard' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'joinBoardWithCode' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'leaveBoard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'lookupUser' : IDL.Func([IDL.Text], [IDL.Opt(UserSearchResult)], ['query']),
  'moveCard' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'removeMember' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'reorderCards' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'reorderColumns' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
  'revokeInvite' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'transferOwnership' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'updateBoard' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateCard' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Principal)],
      [IDL.Bool],
      [],
    ),
  'updateColumn' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateTag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BoardMember = IDL.Record({
    'userId' : IDL.Principal,
    'joinedAt' : Time,
    'role' : IDL.Text,
    'boardId' : IDL.Nat,
  });
  const Tag = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'boardId' : IDL.Nat,
  });
  const Board = IDL.Record({
    'id' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assigneeId' : IDL.Opt(IDL.Principal),
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Nat),
    'description' : IDL.Text,
    'boardId' : IDL.Nat,
    'updatedAt' : Time,
    'position' : IDL.Nat,
    'columnId' : IDL.Nat,
  });
  const Column = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'boardId' : IDL.Nat,
    'position' : IDL.Nat,
  });
  const ColumnWithCards = IDL.Record({
    'cards' : IDL.Vec(Card),
    'column' : Column,
  });
  const BoardWithDetails = IDL.Record({
    'members' : IDL.Vec(BoardMember),
    'tags' : IDL.Vec(Tag),
    'board' : Board,
    'columns' : IDL.Vec(ColumnWithCards),
  });
  const BoardInvite = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'boardId' : IDL.Nat,
    'inviteCode' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'email' : IDL.Text,
  });
  const InviteDetails = IDL.Record({
    'memberCount' : IDL.Nat,
    'boardName' : IDL.Text,
  });
  const UserSearchResult = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Principal,
  });
  
  return IDL.Service({
    'createBoard' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createCard' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Principal)],
        [IDL.Nat],
        [],
      ),
    'createColumn' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createTag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteBoard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteColumn' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTag' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'exportBoardCSV' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'generateBoardInvite' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getBoard' : IDL.Func([IDL.Nat], [IDL.Opt(BoardWithDetails)], ['query']),
    'getBoardInvites' : IDL.Func([IDL.Nat], [IDL.Vec(BoardInvite)], ['query']),
    'getBoardMemberProfiles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getBoardMembers' : IDL.Func([IDL.Nat], [IDL.Vec(BoardMember)], ['query']),
    'getBoardTags' : IDL.Func([IDL.Nat], [IDL.Vec(Tag)], ['query']),
    'getInviteDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InviteDetails)],
        ['query'],
      ),
    'getMyBoards' : IDL.Func([], [IDL.Vec(Board)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserProfile' : IDL.Func([], [IDL.Bool], ['query']),
    'inviteUserToBoard' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'joinBoardWithCode' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'leaveBoard' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'lookupUser' : IDL.Func([IDL.Text], [IDL.Opt(UserSearchResult)], ['query']),
    'moveCard' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'removeMember' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'reorderCards' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'reorderColumns' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Bool], []),
    'revokeInvite' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setUserProfile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'transferOwnership' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'updateBoard' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateCard' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat), IDL.Opt(IDL.Principal)],
        [IDL.Bool],
        [],
      ),
    'updateColumn' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateTag' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };